apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: config-service-image-build-push-
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/component: ci
    service: config-service
spec:
  pipelineRef:
    name: devflow-tekton-image-build-push-only
  params:
    - name: git-url
      value: "GIT_URL_PLACEHOLDER"
    - name: git-revision
      value: "GIT_REVISION_PLACEHOLDER"
    - name: image-registry
      value: "registry.cn-hangzhou.aliyuncs.com/devflow"
    - name: name
      value: "config-service"
    - name: image-tag
      value: "IMAGE_TAG_PLACEHOLDER"
    - name: DOCKERFILE
      value: "Dockerfile"
    - name: BUILD_ARGS
      value: "--build-arg SERVICE_NAME=config-service --build-arg SERVICE_PORT=8082"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: local-path
    - name: dockerconfig
      secret:
        secretName: aliyun-docker-config
    - name: ssh
      secret:
        secretName: git-ssh-secret
  timeouts:
    pipeline: 1h0m0s
