apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg18-production
  namespace: database
  labels:
    app.kubernetes.io/name: pg18-production
    app.kubernetes.io/part-of: devflow
    environment: production
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-minimal-trixie
  instances: 1
  enableSuperuserAccess: false
  monitoring:
    enablePodMonitor: true
  storage:
    size: 20Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: pg18-production-bootstrap-app
      encoding: UTF8
      localeCollate: C
      localeCType: C
