apiVersion: v1
kind: ServiceAccount
metadata:
  name: meta-service
  namespace: devflow
  labels:
    app.kubernetes.io/name: meta-service
    app.kubernetes.io/part-of: devflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-service
  namespace: devflow
  labels:
    app.kubernetes.io/name: config-service
    app.kubernetes.io/part-of: devflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-service
  namespace: devflow
  labels:
    app.kubernetes.io/name: network-service
    app.kubernetes.io/part-of: devflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-service
  namespace: devflow
  labels:
    app.kubernetes.io/name: release-service
    app.kubernetes.io/part-of: devflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runtime-service
  namespace: devflow
  labels:
    app.kubernetes.io/name: runtime-service
    app.kubernetes.io/part-of: devflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-web
  namespace: devflow
  labels:
    app.kubernetes.io/name: platform-web
    app.kubernetes.io/part-of: devflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devflow-meta-service-argocd-devflow
  namespace: argocd
  labels:
    app.kubernetes.io/name: meta-service
    app.kubernetes.io/part-of: devflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devflow-meta-service-argocd
subjects:
  - kind: ServiceAccount
    name: meta-service
    namespace: devflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devflow-release-service-tekton-submit-devflow
  labels:
    app.kubernetes.io/name: release-service
    app.kubernetes.io/part-of: devflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devflow-release-service-tekton-submit
subjects:
  - kind: ServiceAccount
    name: release-service
    namespace: devflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devflow-release-service-argocd-devflow
  namespace: argocd
  labels:
    app.kubernetes.io/name: release-service
    app.kubernetes.io/part-of: devflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devflow-release-service-argocd
subjects:
  - kind: ServiceAccount
    name: release-service
    namespace: devflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runtime-service-runtime-operator-devflow
  labels:
    app.kubernetes.io/name: runtime-service
    app.kubernetes.io/part-of: devflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: runtime-service-runtime-operator
subjects:
  - kind: ServiceAccount
    name: runtime-service
    namespace: devflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runtime-service-tekton-observer-devflow
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: runtime-service
    app.kubernetes.io/part-of: devflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runtime-service-tekton-observer
subjects:
  - kind: ServiceAccount
    name: runtime-service
    namespace: devflow
