apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devflow-meta-service-argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: meta-service
    app.kubernetes.io/part-of: devflow
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devflow-meta-service-argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: meta-service
    app.kubernetes.io/part-of: devflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devflow-meta-service-argocd
subjects:
  - kind: ServiceAccount
    name: meta-service
    namespace: devflow-pre-production
